---
title: "Floor Plan Shell"
author: "Ian Salter"
date: "12/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
devtools::load_all()
```




```{R echo = FALSE}
# distances <- existing_distances()
#distances
```

```{r echo=FALSE}
data("existing_pillars")
ggplot(data = NULL) +
  coord_fixed(ratio = 1) +
  geom_rect(data = existing_pillars,
            color = "darkgray",
            fill = "lightgray",
            aes(xmin = location_x,
                ymin = location_y,
                xmax = location_x + length,
                ymax = location_y + width)
            ) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank())
```

```{R echo = FALSE, out.width="100%", out.length="100%"}
# length_1 <- distance_value(distances, "length_1")
# length_2 <- distance_value(distances, "length_2")
# length_3 <- distance_value(distances, "length_3")
# length_4 <- distance_value(distances, "length_4")
# width_1 <- distance_value(distances, "width_1")
# width_2 <- distance_value(distances, "width_2")
# width_3 <- distance_value(distances, "width_3")
# width_4 <- distance_value(distances, "width_4")
# 
# x1 <- 0.14
# y1 <- 0.38
# x2 <- x1
# y2 <- y1 + length_1 + length_2 + length_3 + length_4
# x3 <- width_4
# y3 <- y2
# x4 <- x3
# y4 <- y2 - length_4  
# x5 <- x4 - (width_4 - width_3)
# y5 <- y4
# x6 <- x5
# y6 <- y5 - length_3
# x7 <- x6 + (width_2 - width_3)
# y7 <- y6
# x8 <- x7
# y8 <- y7 - length_2
# x9 <- x8 + (width_1 - width_2)
# y9 <- y8
# x10 <- x9
# y10 <- y9 - length_1
# 
# coordinate_tbl <- 
#   tibble::tribble(
#     ~x, ~y,
#     x1, y1,
#     x2, y2,
#     x3, y3,
#     x4, y4,
#     x5, y5,
#     x6, y6,
#     x7, y7,
#     x8, y8,
#     x9, y9,
#     x10, y10
#   )
# value_tbl <-
#   tibble::tibble(
#     values = rep(1, times = nrow(coordinate_tbl))
#   )
# 
# 
# datapoly <- dplyr::bind_cols(coordinate_tbl, value_tbl)
# 
# ggplot(data = NULL) +
#   coord_fixed(ratio = 1) +
#   geom_polygon(data = datapoly, aes(x, y)) +
#   geom_rect(data = existing_pillars,
#             color = "darkgray",
#             fill = "lightgray",
#             aes(xmin = location_x,
#                 ymin = location_y,
#                 xmax = location_x + length,
#                 ymax = location_y + width)
#             ) +
#   theme(legend.position = "none",
#         panel.grid = element_blank(),
#         axis.title = element_blank(),
#         axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         panel.background = element_blank())
```


```{R echo = FALSE}
datapoly <-
  tibble::tribble(
    ~x, ~y, ~group,
    0, 0, 1L,
    0, 5, 1L,
    5, 0, 1L,
    1, 1, 2L,
    1, 3, 2L,
    3, 1, 2L,
  )

ggplot(datapoly, aes(x, y)) +
  coord_fixed(ratio = 1) +
  geom_polygon(color = "darkgray", fill = "lightgray", aes(subgroup = group))


```

```{R echo = FALSE}
datapoly <-
  tibble::tribble(
    ~x, ~y, ~id,
    0, 0, "wall_1",
    0, 5, "wall_1",
    1, 5, "wall_1",
    1, 0, "wall_1",
    1, 0, "wall_2",
    1, 1, "wall_2",
    5, 1, "wall_2",
    5, 0, "wall_2"
  )
ggplot(data = NULL) +
  coord_fixed(ratio = 1) +
  geom_polygon(data = datapoly, color = "darkgray", fill = "lightgray", aes(x = x, y = y, group = id))
```




