#' The buildings existing measurements
#'
#' A dataset containing details of the existing measurements for the building.
#'
#' @format A tibble with 10 rows and 7 variables:
#' \describe{
#'   \item{measure}{The name of the measure}
#'   \item{dimension}{The dimension of the measurements}
#'   \item{value}{The value of the measure expressed in meters}
#'   \item{note}{Any textual note concerning the measure}
#' }
#' @source Can be generated by function save_measurements
#' @usage data("measurements")
"measurements"


#' The buildings existing pillars
#'
#' A dataset containing details of the existing pillars in the building.
#'
#' @format A tibble with 10 rows and 10 variables:
#' \describe{
#'   \item{name}{The name of the pillar}
#'   \item{location_x}{The center of the pillar in the x direction}
#'   \item{location_y}{The center of the pillar in the y direction}
#'   \item{location_z}{The center of the pillar in the z direction}
#'   \item{length}{The amount the pillar extends in a north-south, y, direction}
#'   \item{width}{The amount the pillar extends in a east-west, x, direction}
#'   \item{height}{The amount the pillar extends in a top-bottom, z, direction}
#'   \item{start_x}{The x coordinate of the least_vertex }
#'   \item{start_y}{The y coordinate of the least_vertex}
#'   \item{start_z}{The z coordinate of the least_vertex}
#' }
#' @source Can be generated by function save_existing_pillars
#' @usage data("existing_pillars")
"existing_pillars"


#' The buildings existing walls
#'
#' A dataset containing details of the existing walls in the building. Note
#' that for locations the least_vertex is defined as the vertex that has the,
#' smallest x coordinate. If vertices have the same x coordinate, then we take
#' the vertex with the least y coordinate. If vertices have the same x and y
#' corrdinate we take the vertex with the least x_coordinate.
#'
#' @format A tibble with 14 rows and 11 variables:
#' \describe{
#'   \item{name}{The name of the pillar}
#'   \item{location_x}{The center of the wall in the x direction}
#'   \item{location_y}{The center of the wall in the y direction}
#'   \item{location_z}{The center of the wall in the z direction}
#'   \item{length}{The amount the wall extends. When z_rotation is zero length
#'   is measured in the x direction}
#'   \item{width}{The thickness of the wall. When r_rotation is zero width
#'   is measured in the y direction}
#'   \item{height}{The amount extends in a vertical direction}
#'   \item{z_rotation}{The amount the wall is rotated in the z direction. Measured in degrees
#'   counter-clockwise from the x axis.}
#'   \item{start_x}{The x coordinate of the least_vertex }
#'   \item{start_y}{The y coordinate of the least_vertex}
#'   \item{start_z}{The z coordinate of the least_vertex}
#' }
#' @source Can be generated by function save_existing_pillars
#' @usage data("existing_pillars")
"existing_walls"
