#' The buildings existing measurements
#'
#' A dataset containing details of the existing measurements for the building.
#'
#' @format A tibble with 10 rows and 7 variables:
#' \describe{
#'   \item{measure}{The name of the measure}
#'   \item{dimension}{The dimension of the measurements}
#'   \item{value}{The value of the measure expressed in meters}
#'   \item{note}{Any textual note concerning the measure}
#' }
#' @source Can be generated by function save_measurements
#' @usage data("measurements")
"measurements"


#' The buildings existing pillars
#'
#' A dataset containing details of the existing pillars in the building.
#'
#' @format A tibble with 10 rows and 10 variables:
#' \describe{
#'   \item{name}{The name of the pillar}
#'   \item{location_x}{The center of the pillar in the x direction}
#'   \item{location_y}{The center of the pillar in the y direction}
#'   \item{location_z}{The center of the pillar in the z direction}
#'   \item{length}{The amount the pillar extends in a north-south, y, direction}
#'   \item{width}{The amount the pillar extends in a east-west, x, direction}
#'   \item{height}{The amount the pillar extends in a top-bottom, z, direction}
#'   \item{start_x}{The x coordinate of the least_vertex }
#'   \item{start_y}{The y coordinate of the least_vertex}
#'   \item{start_z}{The z coordinate of the least_vertex}
#' }
#' @source Can be generated by function save_existing_pillars
#' @usage data("existing_pillars")
"existing_pillars"


#' The buildings existing walls
#'
#' A dataset containing details of the existing walls in the building. Note
#' that for locations the least_vertex is defined as the vertex that has the,
#' smallest x coordinate. If vertices have the same x coordinate, then we take
#' the vertex with the least y coordinate. If vertices have the same x and y
#' corrdinate we take the vertex with the least x_coordinate.
#'
#' @format A tibble with 14 rows and 11 variables:
#' \describe{
#'   \item{name}{The name of the wall}
#'   \item{location_x}{The center of the wall in the x direction}
#'   \item{location_y}{The center of the wall in the y direction}
#'   \item{location_z}{The center of the wall in the z direction}
#'   \item{length}{The amount the wall extends. When z_rotation is zero length
#'   is measured in the x direction}
#'   \item{width}{The thickness of the wall. When r_rotation is zero width
#'   is measured in the y direction}
#'   \item{height}{The amount extends in a vertical direction}
#'   \item{z_rotation}{The amount the wall is rotated in the z direction. Measured in degrees
#'   counter-clockwise from the x axis.}
#'   \item{start_x}{The x coordinate of the least_vertex }
#'   \item{start_y}{The y coordinate of the least_vertex}
#'   \item{start_z}{The z coordinate of the least_vertex}
#' }
#' @source Can be generated by function save_existing_walls
#' @usage data("existing_walls")
"existing_walls"


#' The buildings existing holes
#'
#' A dataset containing details of the existing holes in building walls. Note
#' that for locations the least_vertex is defined as the vertex that has the,
#' smallest x coordinate. If vertices have the same x coordinate, then we take
#' the vertex with the least y coordinate. If vertices have the same x and y
#' corrdinate we take the vertex with the least x_coordinate.
#'
#' @format A tibble with 14 rows and 11 variables:
#' \describe{
#'   \item{name}{The name of the hole}
#'   \item{wall_name}{The name of the wall of which the hole is a part}
#'   \item{start}{How far from the least vertex of the wall the hole starts}
#'   \item{z_start}{How far from the bottom of the wall the hole starts.}
#'   \item{length}{The length of the hole along the walls direction}
#'   \item{height}{How hight the hole extends from the z_start.}
#' }
#' @source Can be generated by function save_existing_holes
#' @usage data("existing_holes")
"existing_holes"


#' The buildings new walls
#'
#' A dataset containing details of the new walls in the building. Note
#' that for locations the least_vertex is defined as the vertex that has the,
#' smallest x coordinate. If vertices have the same x coordinate, then we take
#' the vertex with the least y coordinate. If vertices have the same x and y
#' corrdinate we take the vertex with the least x_coordinate.
#'
#' @format A tibble with 14 rows and 11 variables:
#' \describe{
#'   \item{name}{The name of the wall}
#'   \item{location_x}{The center of the wall in the x direction}
#'   \item{location_y}{The center of the wall in the y direction}
#'   \item{location_z}{The center of the wall in the z direction}
#'   \item{length}{The amount the wall extends. When z_rotation is zero length
#'   is measured in the x direction}
#'   \item{width}{The thickness of the wall. When r_rotation is zero width
#'   is measured in the y direction}
#'   \item{height}{The amount extends in a vertical direction}
#'   \item{z_rotation}{The amount the wall is rotated in the z direction. Measured in degrees
#'   counter-clockwise from the x axis.}
#'   \item{start_x}{The x coordinate of the least_vertex}
#'   \item{start_y}{The y coordinate of the least_vertex}
#'   \item{start_z}{The z coordinate of the least_vertex}
#' }
#' @source Can be generated by function save_existing_walls
#' @usage data("new_walls")
"new_walls"

#' The buildings new windows and doors
#'
#' A dataset containing details of the new walls in the building. Note
#' that for locations the least_vertex is defined as the vertex that has the,
#' smallest x coordinate. If vertices have the same x coordinate, then we take
#' the vertex with the least y coordinate. If vertices have the same x and y
#' corrdinate we take the vertex with the least x_coordinate.
#'
#' @format A tibble with 14 rows and 13 variables:
#' \describe{
#'   \item{name}{The name of the window}
#'   \item{wall_name}{The name of the wall of which this window is a part}
#'   \item{type}{One of the various FreeCAD arch workbench window types}
#'   \item{start}{The location at which the window starts on the wall}
#'   \item{z_start}{The height at which the window starts}
#'   \item{width}{The overall width of the window}
#'   \item{height}{The overall height of the window}
#'   \item{h1}{The height of the top of the frame}
#'   \item{h2}{The height of the top of the window casement}
#'   \item{h3}{The height of a bottom Pannel on a glass door}
#'   \item{w1}{Overall width of the window doorframe.}
#'   \item{w2}{Width of the actual window}
#'   \item{o1}{Distance of the frame from the inside of the building}
#'   \item{o2}{Distance of the window from the start of the frame inside}
#' }
#' @source Can be generated by function save_new_windows
#' @usage data("new_windows")
"new_windows"
